In [1]:
var = 12
print(var)
print(type(var))

12
<class 'int'>


In [2]:
vf = 2.0

print(vf)
print(type(vf))

2.0
<class 'float'>


In [3]:
var = float(var)

print(var)
print(type(var))

12.0
<class 'float'>


In [4]:
var = str(var)

print(var)
print(type(var))

12.0
<class 'str'>


In [5]:
array = [0,3,6,9]

print(array)

[0, 3, 6, 9]


In [6]:
import numpy as np
array = np.array(array)

print(array)

[0 3 6 9]


In [8]:
array[:] = 0
print(array)

[0 0 0 0]


In [9]:
array[:] = 1
print(array)

[1 1 1 1]


In [10]:
a = np.array([1,2,3,4])
b = np.array([0,1,1,0])
c = np.array(a + b)
print(c)

[1 3 4 4]


In [15]:
n = np.zeros(4,np.int)
q = np.zeros(shape=(2,3,5),dtype=float)
l = np.full(100,1.0e20)
print(n)
print(q)
print(l)

[0 0 0 0]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20
 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [16]:
a_sub = a[1:3]
print(a_sub)
a_sub = a[1:4]
print(a_sub)

[2 3]
[2 3 4]


In [17]:
a_rev = a[::-1]
print(a_rev)

[4 3 2 1]


In [18]:
a_sec = a[::2]
print(a_sec)

[1 3]


In [33]:
ind_not0 = np.nonzero(b)
print(b[ind_not0])

[1 1]


In [34]:
i = np.arange(0,10,1)
print(i)

lat = np.arange(-180.0,210.0,30.0)
print(lat)

[0 1 2 3 4 5 6 7 8 9]
[-180. -150. -120.  -90.  -60.  -30.    0.   30.   60.   90.  120.  150.
  180.]


In [37]:
ra = np.array([[[1,2,3,4],[5,6,7,8],[5,4,2,0]],
               [[1,2,3,4],[5,6,7,8],[5,4,2,0]]])
print(ra.shape)
ra1d = np.ravel(ra)
print(ra1d)
print(ra.reshape(-1))
print(len(ra1d))
print(ra.shape)
print("---")
ra3d = np.reshape(ra,ra.shape)
print(ra3d.shape)

(2, 3, 4)
[1 2 3 4 5 6 7 8 5 4 2 0 1 2 3 4 5 6 7 8 5 4 2 0]
[1 2 3 4 5 6 7 8 5 4 2 0 1 2 3 4 5 6 7 8 5 4 2 0]
24
(2, 3, 4)
---
(2, 3, 4)


In [39]:
t = 99
if t == 0:
	print("t = 0")
elif t == 1:
	print("t = 1")
else:
	print(f"t = {t}")

t = 99


In [41]:
for j in range(0,5,1):
	print(f"j = {j}")

str_array = ["Hamburg","Munich","Berlin"]

for city in str_array:
	print(city)

j = 0
j = 1
j = 2
j = 3
j = 4
Hamburg
Munich
Berlin


In [43]:
j = 0
while(j <= 5):
	print("j = ",j)
	if j == 3:
		print(f"--> j = {j}")
	j = j + 1

j =  0
j =  1
j =  2
j =  3
--> j = 3
j =  4
j =  5
